//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoPartido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipoPartido()
        {
            this.Resultadoes = new HashSet<Resultado>();
        }
    
        public int IdEquipoPartido { get; set; }
        public Nullable<int> IdEquipo { get; set; }
        public Nullable<int> Gol { get; set; }
        public Nullable<int> IdPartido { get; set; }
        public Nullable<int> IdEquipoVisita { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Equipo Equipo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultado> Resultadoes { get; set; }
        public virtual Partido Partido { get; set; }
    }
}
